routes/admin.php
<?php
use App\Http\Controllers\Admin\AcceptController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/admin/users');
});

 Route::middleware("guest:admin")->group(function() {
    Route::get('login', [\App\Http\Controllers\Admin\AuthController::class, 'index'])->name('login');
    Route::post('login_process', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login_process');
 });

 Route::middleware("auth:admin")->group(function() {
    Route::get('logout', [\App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');
    Route::resource('admin_users', \App\Http\Controllers\Admin\AdminUserController::class);
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    Route::resource('message', \App\Http\Controllers\Admin\MessagesController::class);
    Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
    Route::resource('states', \App\Http\Controllers\Admin\SendStateController::class);
    Route::get('/admin/states/accept', [AcceptController::class, 'accept'])->name('states.accept');
    Route::get('/admin/states/reject', [AcceptController::class, 'reject'])->name('states.reject');
});

routes/web.php
<?php

use App\Http\Controllers\IndexController;

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use App\Http\Middleware;



Route::get('/setlocale/{locale}', [IndexController::class, 'setLocale'])->name('setlocale'); 

Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
Route::get('/emails/email', [\App\Http\Controllers\IndexController::class, 'getEmail']);

Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('home');

Route::middleware('auth')->group(function(){
    Route::get('/profile', [\App\Http\Controllers\ProfileController::class, 'show'])->name('profile.index');
    Route::post('/profile_store', [\App\Http\Controllers\ProfileController::class, 'store'])->name('profile.store');

    Route::get('/states/index', function(){ return view('/states/index'); });
    Route::get('/publication/index', [App\Http\Controllers\SendStateControllerStep1::class, 'publication'])->name('pubclication');
    Route::get('/publication/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('publication.show');
    Route::get('/publication/pages/', [\App\Http\Controllers\SendStateControllerStep1::class, 'pages']);
    Route::get('/publication/index/{id}', [\App\Http\Controllers\SendStateControllerStep1::class, 'show'])->name('publication.show');

    Route::get('/submited/index', [App\Http\Controllers\SendStateControllerStep1::class, 'getState']); 
    Route::get('/states/step1', [App\Http\Controllers\SendStateControllerStep1::class, 'createStep1']); 
    Route::post('/states/step1', [App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep1']); 
    Route::get('/states/step2', [App\Http\Controllers\SendStateControllerStep1::class, 'createStep2']); 
    Route::post('/states/step2', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep2']);
    Route::get('/states/step3', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep3']); 
    Route::post('/states/step3', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep3']); 
    Route::get('/states/step4', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep4']); 
    Route::post('/states/step4', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep4']); 
    Route::get('/states/step5', [\App\Http\Controllers\SendStateControllerStep1::class,'createStep5']); 
    Route::post('/states/step5', [\App\Http\Controllers\SendStateControllerStep1::class,'postCreateStep5']); 
    Route::get('/states/step6', [\App\Http\Controllers\SendStateControllerStep1::class,'createStep6']); 
    Route::post('/states/step6', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep6']); 
    Route::get('/states/step9', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep9']); 
    Route::post('/states/store', [\App\Http\Controllers\SendStateControllerStep1::class, 'store']); 
});

    Route::get('/posts/index', [\App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
    Route::get('/posts/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('posts.show');
    Route::get('/publication/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('publication.show');
    Route::get('/posts/first', [\App\Http\Controllers\PostController::class, 'first'])->name('posts.first');

Route::middleware("auth:web")->group(function () {
    Route::get('/logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');
    Route::post('/posts/comment/{id}', [\App\Http\Controllers\PostController::class, 'comment'])->name('comment');
    Route::get('/message/index', [\App\Http\Controllers\MessageController::class, 'show'])->name('message.index');
    Route::get('/message/send', [\App\Http\Controllers\MessageController::class, 'send'])->name('message.send');
    Route::get('/message/sended', [\App\Http\Controllers\MessageController::class, 'sended'])->name('message.sended');
    Route::post('/message/index', [App\Http\Controllers\MessageController::class, 'sendMsg'])->name('sendMsg');
});

Route::middleware("guest:web")->group(function () {
    Route::get('/login', [\App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
    Route::post('/login_process', [\App\Http\Controllers\AuthController::class, 'login'])->name('login_process');

    Route::get('/register', [\App\Http\Controllers\AuthController::class, 'showRegisterForm'])->name('register');
    Route::post('/register_process', [\App\Http\Controllers\AuthController::class, 'register'])->name('register_process');

    Route::get('/forgot', [\App\Http\Controllers\AuthController::class, 'showForgotForm'])->name('forgot');
    Route::post('/forgot_process', [\App\Http\Controllers\AuthController::class, 'forgot'])->name('forgot_process');
});

// Route::post('/admin/states', \App\Http\Controllers\Admin\AcceptController::class, 'approve')->name('admin.approve');
// Route::post('/admin/states', \App\Http\Controllers\Admin\AcceptController::class, 'decline')->name('admin.decline');

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Message extends Model
{
    use HasFactory;

    protected $fillable = ['recipient, subject, body'];
    
    protected $appends = ['selfMessage'];

    public function getSelfMessageAttribute()
    {
        return $this->user_id === auth()->user()->id;
    }
    // public function user()
    // {
    //     return $this->belongsTo(AdminUser::class);
    // }
 }

app/Http/Controllers/Admin/MessagesController.php
<?php

namespace App\Http\Controllers\Admin;
use App\Http\Controllers\Controller;
use App\Models\AdminUser;
use App\Models\Message;
use Carbon\Carbon;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Database\Eloquent\ModelNotFoundException;
use Illuminate\Support\Facades\Auth;

class MessagesController extends Controller
{
    /**
     * Show all of the message threads to the user.
     *
     * @return mixed
     */
    public function index()
    {
        return view('admin.message.index',[
            'users' => User::all(),
        ]);
    }


    public function sendMessageTo($recipient, $message, $subject)
    {
        return $this->sent()->create([
            'body'       => $message,
            'subject'    => $subject,
            'sent_to_id' => $recipient,
        ]);   
    }
    
    public function SendMessage(Request $request){
        AdminUser::user()->sendMessageTo(1, $request->subject, $request->body);
}
    // public function index()
    // {
    //     return view('admin.message.index',[
    //         'users' => AdminUser::all(),
    //         ]);
    // }
    public function store(Request $request)
    {
        $message = Message::create([
            'subject' => $request->subject,
            'body' => $request->subject,
        ]);

        // Message
        Message::create([
            'sent_to_id' => $message->id,
            'sender_id' => Auth::id(),
            'body' => $request->message,
        ]);

        // Recipients
        $message->addParticipant($request->recipient);

        return redirect()->route('admin.message.index')->with('success', 'Message sent successfully.');
    }
 

    public function show(){
        return view('/message/send',[
            'admins' => AdminUser::all(),
        ]); 
    }
public function composeMessage()
{
    // ...

    // Get a collection of `[id => name]` probable recipients,
    // so that the logged-in user can choose from. Note that 
    // you probably want to exclude the current user herself
    // from the list.
    return view('admin.message.index',[
    'users' => AdminUser::all(),
    ]);
// AdminUser::where('id', '!=', Auth::id())->pluck('name', 'id')]);    
}
 
 
 
     // public function index()
    // {
    //     $threads = Thread::forUser(Auth::id())
    //         ->withCount('messages')
    //         ->latest()
    //         ->get()
    //         ->reject(function ($value) {
    //             return $value->messages_count == 1 && $value->creator() == Auth::user();
    //         });

    //     return view('messenger.index', compact('threads'));
    // }

    // /**
    //  * Shows a message thread.
    //  *
    //  * @param $id
    //  * @return mixed
    //  */
    // public function show(Thread $thread)
    // {
    //     $thread->markAsRead(Auth::id());

    //     return view('messenger.show', compact('thread'));
    // }

    // /**
    //  * Creates a new message thread.
    //  *
    //  * @return mixed
    //  */
    // public function create()
    // {
    //     $users = User::where('id', '!=', Auth::id())->get();

    //     return view('messenger.create', compact('users'));
    // }

    // /**
    //  * Stores a new message thread.
    //  *
    //  * @return mixed
    //  */
    // public function store(Request $request)
    // {
    //     $thread = Thread::create([
    //         'subject' => $request->subject,
    //     ]);

    //     // Message
    //     Message::create([
    //         'thread_id' => $thread->id,
    //         'user_id' => Auth::id(),
    //         'body' => $request->message,
    //     ]);

    //     // Sender
    //     Participant::create([
    //         'thread_id' => $thread->id,
    //         'user_id' => Auth::id(),
    //         'last_read' => new Carbon,
    //     ]);

    //     // Recipients
    //     $thread->addParticipant($request->recipient);

    //     return redirect()->route('messages')->with('success', 'Message sent successfully.');
    // }

    // /**
    //  * Adds a new message to a current thread.
    //  *
    //  * @param $id
    //  * @return mixed
    //  */
    // public function update(Request $request, Thread $thread)
    // {
    //     $thread->activateAllParticipants();

    //     Message::create([
    //         'thread_id' => $thread->id,
    //         'user_id' => Auth::id(),
    //         'body' => $request->message,
    //     ]);

    //     $participant = Participant::firstOrCreate([
    //         'thread_id' => $thread->id,
    //         'user_id' => Auth::id(),
    //     ]);

    //     $participant->last_read = new Carbon;
    //     $participant->save();

    //     return redirect()->route('messages')->with('success', 'Reply sent successfully.');
    // }

    // public function destroy(Thread $thread)
    // {
    //     $thread->removeParticipant(Auth::id());

    //     return redirect()->route('messages')->with('success', 'Thread deleted successfully.');
    // }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Models\AdminUser;
use App\Models\Message;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class MessageController extends Controller
{
   

    public function send(){
        return view('message.send',[
            'admins' => AdminUser::all(),
        ]);
    }
    public function show(){
        return view('message.index',[
            'admins' => AdminUser::all(),
        ]);
    }
    public function sended(){
        return view('message.sended',[
            'messages' => Message::all(),
        ]);
    }
    public function showid($id)
    {
        $post = Message::findOrFail($id);

        return view('message.sended', [
            "messages" => Message::all(),
        ]);
    }

    public function sendMsg(Request $request){
        $validatedData = $request->validate([
        'recipient'=> 'required', 
        'subject' => 'required', 
        'message' => 'required',
       ]);
       $msg = Message::create([
        "recipient" => $validatedData["recipient"],
        "subject" => $validatedData["subject"],
        "message" => $validatedData["message"],
       ]);
       redirect('/message/index');
    }
}

app/Http/Livewire/Admin/Messages/ListConversationAndMessages.php
<?php

namespace App\Http\Livewire\Admin\Message;
use App\Models\Conversation;
use App\Models\Message;
use Livewire\Component;

class Php extends Component
{
   
    public $body;

    public $selectedConversation;

    public function mount()
    {
        if (session()->has('selectedConversation')) {
            return $this->selectedConversation = session('selectedConversation');
        }

        $this->selectedConversation = Conversation::query()
            ->where('sender_id', auth()->id())
            ->orWhere('receiver_id', auth()->id())
            ->first();
    }

    public function sendMessage()
    {
        Message::create([
            'conversation_id' => $this->selectedConversation->id,
            'user_id' => auth()->id(),
            'body' => $this->body
        ]);

        $this->reset('body');

        $this->viewMessage($this->selectedConversation->id);
    }

    public function viewMessage($conversationId)
    {
        $this->selectedConversation = Conversation::findOrFail($conversationId);
    }

    public function render()
    {
        $conversations = Conversation::query()
            ->where('sender_id', auth()->id())
            ->orWhere('receiver_id', auth()->id())
            ->get();

        return view('livewire.admin.messages.list-conversation-and-messages', [
            'conversations' => $conversations
        ]);
    }
}

resources/views/admin/message/create.blade.php
@extends('layout.admin')

@section('title',  isset($message) ? "Редактировать статью ID {$message->id}" : 'Отправить сообщения')

@section('content')
    <div class="container mx-auto px-6 py-8">
        <h3 class="text-gray-700 text-3xl font-medium">{{ isset($message) ? "Редактировать статью ID {$message->id}" : 'Добавить статью' }}</h3>

        <div class="mt-8">

        </div>

        <div class="mt-8">
            <form enctype="multipart/form-data" class="space-y-5 mt-5" method="message" action="{{ isset($message) ? route('admin.message.update', $message->id) : route("admin.message.store") }}">
                @csrf

                @if(isset($message))
                    @method('PUT')
                @endif

                <input name="subject" type="text" class="w-full h-12 border border-gray-800 rounded px-3 @error('subject') border-red-500 @enderror" placeholder="Subject" value="{{ $message->subject ?? '' }}" />

                @error('subject')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror


                <input name="message" type="text" class="w-full h-12 border border-gray-800 rounded px-3 @error('message') border-red-500 @enderror" placeholder="Описание" value="{{ $message->message ?? '' }}" />

                @error('message')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                
                <button type="submit" class="text-center w-full bg-blue-900 rounded-md text-white py-3 font-medium">Сохранить</button>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/message/index.blade.php
@extends('layout.admin')

@section('title', 'Сообщения')

@section('content')

<div class="container">
<div class="row inbox">
	<div class="col-md-3">
		<div class="panel panel-default">
			<div class="panel-body inbox-menu">						
				
				<ul>
					<li>
						<a href="/message/sended"><i class="fa fa-inbox"></i> @lang('index.olingan') <span class="label label-danger"></span></a>
					</li>
					<br>
					<li>
						<a href="/message/sended"><i class="fa fa-rocket"></i> @lang('index.yubor')</a>
					</li>
				<br></a>
	</ul>
			</div>	
		</div>
		
			
		
	</div><!--/.col-->
	
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-body message">
				<h3 class="text-center">@lang('index.xabar')</h3>
				<form action="/message/index" class="form-horizontal" method="POST" role="form">
					@csrf
					<div class="form-group">
				    	<label for="to" class="col-sm-1 control-label">@lang('index.kim'):</label>
				    	<div class="col-sm-11">  
							  <select class="form-control select2-offscreen" id="to" name="recipient" >
                              @foreach($users as $user)
										<option value="{{$user->id}}">{{$user->name}} {{$user->surname}}</option>
										@endforeach	
           					 </select>
				    	</div>
				  	</div>
					<div class="form-group">
				    	<label for="cc" class="col-sm-1 control-label">@lang('index.mavzu'):</label>
				    	<div class="col-sm-11">
                              <input type="text" class="form-control select2-offscreen" name="subject" id="cc" placeholder="" tabindex="-1">
				    	</div>
				  	</div>
					<div class="col-sm-11 col-sm-offset-1">	<br>		
						<div class="form-group">
							<label for="bcc" class="col-sm-1 control-label">@lang('index.text'):</label>
							<textarea class="form-control" id="message" name="body" rows="12" placeholder=""></textarea>
						</div>
					
					<div class="form-group">	
						<button type="submit" class="btn btn-success" onclick="alert('Ваше сообщение было отправлено')">@lang('index.send')</button>	
					</div>
					</form>
				</div>	
			</div>	
		</div>	
	</div>	
</div>
</div>
<script>
	$(document).ready(function(){
    $("#to, #cc, #bcc").select2({tags:["team@bm.com", "ceo@bm.com", "cto@bm.com"]});
});
</script>
@endsection 