routes/admin.php
<?php
use App\Http\Controllers\Admin\AcceptController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/admin/users');
});

 Route::middleware("guest:admin")->group(function() {
    Route::get('login', [\App\Http\Controllers\Admin\AuthController::class, 'index'])->name('login');
    Route::post('login_process', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login_process');
 });

 Route::middleware("auth:admin")->group(function() {
    Route::get('logout', [\App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');
    Route::resource('admin_users', \App\Http\Controllers\Admin\AdminUserController::class);
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    Route::resource('message', \App\Http\Controllers\Admin\MessagesController::class);
    Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
    Route::resource('states', \App\Http\Controllers\Admin\SendStateController::class);
    Route::get('/admin/states/accept', [AcceptController::class, 'accept'])->name('states.accept');
    Route::get('/admin/states/reject', [AcceptController::class, 'reject'])->name('states.reject');
});

routes/web.php
<?php

use App\Http\Controllers\IndexController;

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use App\Http\Middleware;



Route::get('/setlocale/{locale}', [IndexController::class, 'setLocale'])->name('setlocale'); 

Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
Route::get('/emails/email', [\App\Http\Controllers\IndexController::class, 'getEmail']);

Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('home');

Route::middleware('auth')->group(function(){
    Route::get('/profile', [\App\Http\Controllers\ProfileController::class, 'show'])->name('profile.index');
    Route::post('/profile_store', [\App\Http\Controllers\ProfileController::class, 'store'])->name('profile.store');

    Route::get('/states/index', function(){ return view('/states/index'); });
    Route::get('/publication/index', [App\Http\Controllers\SendStateControllerStep1::class, 'publication'])->name('pubclication');
    Route::get('/publication/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('publication.show');
    Route::get('/publication/pages/', [\App\Http\Controllers\SendStateControllerStep1::class, 'pages']);
    Route::get('/publication/index/{id}', [\App\Http\Controllers\SendStateControllerStep1::class, 'show'])->name('publication.show');

    Route::get('/submited/index', [App\Http\Controllers\SendStateControllerStep1::class, 'getState']); 
    Route::get('/states/step1', [App\Http\Controllers\SendStateControllerStep1::class, 'createStep1']); 
    Route::post('/states/step1', [App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep1']); 
    Route::get('/states/step2', [App\Http\Controllers\SendStateControllerStep1::class, 'createStep2']); 
    Route::post('/states/step2', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep2']);
    Route::get('/states/step3', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep3']); 
    Route::post('/states/step3', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep3']); 
    Route::get('/states/step4', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep4']); 
    Route::post('/states/step4', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep4']); 
    Route::get('/states/step5', [\App\Http\Controllers\SendStateControllerStep1::class,'createStep5']); 
    Route::post('/states/step5', [\App\Http\Controllers\SendStateControllerStep1::class,'postCreateStep5']); 
    Route::get('/states/step6', [\App\Http\Controllers\SendStateControllerStep1::class,'createStep6']); 
    Route::post('/states/step6', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep6']); 
    Route::get('/states/step9', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep9']); 
    Route::post('/states/store', [\App\Http\Controllers\SendStateControllerStep1::class, 'store']); 
});

    Route::get('/posts/index', [\App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
    Route::get('/posts/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('posts.show');
    Route::get('/publication/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('publication.show');
    Route::get('/posts/first', [\App\Http\Controllers\PostController::class, 'first'])->name('posts.first');

Route::middleware("auth:web")->group(function () {
    Route::get('/logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');
    Route::post('/posts/comment/{id}', [\App\Http\Controllers\PostController::class, 'comment'])->name('comment');
    Route::get('/message/index', [\App\Http\Controllers\MessageController::class, 'show'])->name('message.index');
    Route::get('/message/send', [\App\Http\Controllers\MessageController::class, 'send'])->name('message.send');
    Route::get('/message/sended', [\App\Http\Controllers\MessageController::class, 'sended'])->name('message.sended');
    Route::post('/message/index', [App\Http\Controllers\MessageController::class, 'sendMsg'])->name('sendMsg');
});

Route::middleware("guest:web")->group(function () {
    Route::get('/login', [\App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
    Route::post('/login_process', [\App\Http\Controllers\AuthController::class, 'login'])->name('login_process');

    Route::get('/register', [\App\Http\Controllers\AuthController::class, 'showRegisterForm'])->name('register');
    Route::post('/register_process', [\App\Http\Controllers\AuthController::class, 'register'])->name('register_process');

    Route::get('/forgot', [\App\Http\Controllers\AuthController::class, 'showForgotForm'])->name('forgot');
    Route::post('/forgot_process', [\App\Http\Controllers\AuthController::class, 'forgot'])->name('forgot_process');
});

// Route::post('/admin/states', \App\Http\Controllers\Admin\AcceptController::class, 'approve')->name('admin.approve');
// Route::post('/admin/states', \App\Http\Controllers\Admin\AcceptController::class, 'decline')->name('admin.decline');

app/Models/AdminUser.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class AdminUser extends Authenticatable
{
    use HasFactory;

   

    protected $fillable = [
        "name",
        "role",
        "email",
        "password"
    ];
    // public function messages()
    // {
    //     return $this->hasMany(Message::class);
    // }

    // // A user can also receive a message
    // public function received()
    // {
    //     return $this->hasMany(Message::class, 'sent_to_id');
    // }

    // public function sendMessageTo($recipient, $message, $subject)
    // {
    //     return $this->sent()->create([
    //         'body'       => $message,
    //         'subject'    => $subject,
    //         'sent_to_id' => $recipient,
    //     ]);   
    

    
    public function setPasswordAttribute($value)
    {
        $this->attributes['password'] = bcrypt($value);
    }
}

app/Http/Controllers/Admin/AdminUserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\AdminUserFormRequest;
use App\Models\AdminUser;

class AdminUserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = AdminUser::orderBy("created_at", "DESC")->paginate(8);

        return view("admin.admin_users.index", [
            "users" => $users,
        ]);
    }
    

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view("admin.admin_users.create");
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  AdminUserFormRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminUserFormRequest $request)
    {
        $data = $request->validated();

        AdminUser::create($data);

        return redirect(route("admin.admin_users.index"));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = AdminUser::findOrFail($id);

        return view("admin.admin_users.create", [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  AdminUserFormRequest  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminUserFormRequest $request, $id)
    {
        $user = AdminUser::findOrFail($id);

        $user->update($request->validated());

        return redirect(route("admin.admin_users.index"));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        AdminUser::destroy($id);

        return redirect(route("admin.admin_users.index"));
    }
}

resources/views/admin/admin_users/create.blade.php
@extends('layout.admin')

@section('title',  isset($user) ? "Редактировать пользователя ID {$user->id}" : 'Добавить пользователя')

@section('content')
    <div class="container mx-auto px-6 py-8">
        <h2 class="form_title mb-4">{{ isset($user) ? "Редактировать пользователя ID {$user->id}" : 'Добавить пользователя' }}</h2>

        <div class="mt-8">

        </div>

        <div class="mt-8">
            <form enctype="multipart/form-data" class="space-y-5 mt-5" method="POST" action="{{ isset($user) ? route('admin.admin_users.update', $user->id) : route('admin.admin_users.store') }}">
                @csrf

                @if(isset($user))
                <div class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <input type="hidden" name="id" class="form_input" value="{{ $user->id }}"/>
                </div>
                    @method('PUT')
                @endif
                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Email:</label>
                    <input name="email" type="text" class="form_input" placeholder="E-mail" value="{{ $user->email ?? '' }}" />
                </div>
                @error('email')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror
                <br>
                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Имя:</label>
                    <input name="name" type="text" class="form_input" placeholder="Имя" value="{{ $user->name ?? '' }}" />
                </div>
                @error('name')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror
                <br>
                <div class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Роль:</label>
                    <select class="form_input" aria-label="Default select example" name="role" value="{{ $user->role ?? ' ' }}">
                        <option>Главный редактор</option>
                        <option>Редактор</option>
                    </select>
                </div>
                @error('role')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror
                <br>
                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Пароль</label>
                    <input name="password" type="password" autocomplete="new-password" class="form_input" placeholder="Пароль" value="" />
                </div>
                <br>
                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Потвердите пароль</label>
                    <input name="password_confirmation" type="password" autocomplete="new-password"  class="form_input" placeholder="Подтверждение пароля" value="" />
                </div>
                @error('password')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                <div class="d-flex flex-column gap-2 w-100" style="max-width: 750px;">
                    <button type="submit" class="form_btn mx-auto text-decoration-none mt-5 padding-right-10">Сoxранить</button>
                </div>
            </form>
        </div>
    </div>
    </div>
@endsection

resources/views/admin/admin_users/index.blade.php
@extends('layout.admin')

@section('title', 'Администраторы')

@section('content')
<h3 class="text-gray-700 text-3xl font-medium">Администраторы</h3>
<br>
  <div>
    <a class="btn btn-info text-white" href="{{ route('admin.admin_users.create')}}">Добавить</a>
  </div>
  <div>
    <input class="form-control mb-6" type="text" placeholder="Поиск" id="search-text" onkeyup="tableSearch()" style="width: 300px; float:right">
    <table class="table table-striped" id="info-table">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Имя</th>
                <th scope="col">Email</th>
                <th scope="col">Роль</th>
                <th scope="col">Действия</th>
              </tr>
            </thead>
            @foreach($users as $user)
            <tbody>
              <tr>
                <th scope="row">1</th>
                <td>{{$user -> name}}</td>
                <td>{{$user -> email}}</td>
                <td>{{$user -> role}}</td>
                <td class="d-flex gap-3 align-items-start">
                    <a class="btn btn-info text-white" href="{{ route('admin.admin_users.edit', $user->id) }}">Редактировать</a>
                   
                    <form action="{{ route('admin.admin_users.destroy', $user->id) }}" method="POST">
                        @csrf
                            @method('DELETE')
                        <button type="submit" class="btn btn-danger h-auto" onclick="func()">Удалить</button>
                    </form>
                </td>
                @endforeach
              </tr>
            </tbody>
          </table>
  </div>
          <script>
 function tableSearch() {
    var phrase = document.getElementById('search-text');
    var table = document.getElementById('info-table');
    var regPhrase = new RegExp(phrase.value, 'i');
    var flag = false;
    for (var i = 1; i < table.rows.length; i++) {
        flag = false;
        for (var j = table.rows[i].cells.length - 1; j >= 0; j--) {
            flag = regPhrase.test(table.rows[i].cells[j].innerHTML);
            if (flag) break;
        }
        if (flag) {
            table.rows[i].style.display = "";
        } else {
            table.rows[i].style.display = "none";
        }

    }
}
</script>
@endsection