routes/admin.php
<?php
use App\Http\Controllers\Admin\AcceptController;
use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return redirect('/admin/users');
});

 Route::middleware("guest:admin")->group(function() {
    Route::get('login', [\App\Http\Controllers\Admin\AuthController::class, 'index'])->name('login');
    Route::post('login_process', [\App\Http\Controllers\Admin\AuthController::class, 'login'])->name('login_process');
 });

 Route::middleware("auth:admin")->group(function() {
    Route::get('logout', [\App\Http\Controllers\Admin\AuthController::class, 'logout'])->name('logout');
    Route::resource('admin_users', \App\Http\Controllers\Admin\AdminUserController::class);
    Route::resource('posts', \App\Http\Controllers\Admin\PostController::class);
    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    Route::resource('message', \App\Http\Controllers\Admin\MessagesController::class);
    Route::resource('profile', \App\Http\Controllers\Admin\ProfileController::class);
    Route::resource('states', \App\Http\Controllers\Admin\SendStateController::class);
    Route::get('/admin/states/accept', [AcceptController::class, 'accept'])->name('states.accept');
    Route::get('/admin/states/reject', [AcceptController::class, 'reject'])->name('states.reject');
});

routes/web.php
<?php

use App\Http\Controllers\IndexController;

use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use App\Http\Middleware;



Route::get('/setlocale/{locale}', [IndexController::class, 'setLocale'])->name('setlocale'); 

Route::get('/welcome', [\App\Http\Controllers\IndexController::class, 'welcome'])->name('welcome');
Route::get('/emails/email', [\App\Http\Controllers\IndexController::class, 'getEmail']);

Route::get('/', [\App\Http\Controllers\IndexController::class, 'index'])->name('home');

Route::middleware('auth')->group(function(){
    Route::get('/profile', [\App\Http\Controllers\ProfileController::class, 'show'])->name('profile.index');
    Route::post('/profile_store', [\App\Http\Controllers\ProfileController::class, 'store'])->name('profile.store');

    Route::get('/states/index', function(){ return view('/states/index'); });
    Route::get('/publication/index', [App\Http\Controllers\SendStateControllerStep1::class, 'publication'])->name('pubclication');
    Route::get('/publication/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('publication.show');
    Route::get('/publication/pages/', [\App\Http\Controllers\SendStateControllerStep1::class, 'pages']);
    Route::get('/publication/index/{id}', [\App\Http\Controllers\SendStateControllerStep1::class, 'show'])->name('publication.show');

    Route::get('/submited/index', [App\Http\Controllers\SendStateControllerStep1::class, 'getState']); 
    Route::get('/states/step1', [App\Http\Controllers\SendStateControllerStep1::class, 'createStep1']); 
    Route::post('/states/step1', [App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep1']); 
    Route::get('/states/step2', [App\Http\Controllers\SendStateControllerStep1::class, 'createStep2']); 
    Route::post('/states/step2', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep2']);
    Route::get('/states/step3', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep3']); 
    Route::post('/states/step3', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep3']); 
    Route::get('/states/step4', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep4']); 
    Route::post('/states/step4', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep4']); 
    Route::get('/states/step5', [\App\Http\Controllers\SendStateControllerStep1::class,'createStep5']); 
    Route::post('/states/step5', [\App\Http\Controllers\SendStateControllerStep1::class,'postCreateStep5']); 
    Route::get('/states/step6', [\App\Http\Controllers\SendStateControllerStep1::class,'createStep6']); 
    Route::post('/states/step6', [\App\Http\Controllers\SendStateControllerStep1::class, 'postCreateStep6']); 
    Route::get('/states/step9', [\App\Http\Controllers\SendStateControllerStep1::class, 'createStep9']); 
    Route::post('/states/store', [\App\Http\Controllers\SendStateControllerStep1::class, 'store']); 
});

    Route::get('/posts/index', [\App\Http\Controllers\PostController::class, 'index'])->name('posts.index');
    Route::get('/posts/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('posts.show');
    Route::get('/publication/{id}', [\App\Http\Controllers\PostController::class, 'show'])->name('publication.show');
    Route::get('/posts/first', [\App\Http\Controllers\PostController::class, 'first'])->name('posts.first');

Route::middleware("auth:web")->group(function () {
    Route::get('/logout', [\App\Http\Controllers\AuthController::class, 'logout'])->name('logout');
    Route::post('/posts/comment/{id}', [\App\Http\Controllers\PostController::class, 'comment'])->name('comment');
    Route::get('/message/index', [\App\Http\Controllers\MessageController::class, 'show'])->name('message.index');
    Route::get('/message/send', [\App\Http\Controllers\MessageController::class, 'send'])->name('message.send');
    Route::get('/message/sended', [\App\Http\Controllers\MessageController::class, 'sended'])->name('message.sended');
    Route::post('/message/index', [App\Http\Controllers\MessageController::class, 'sendMsg'])->name('sendMsg');
});

Route::middleware("guest:web")->group(function () {
    Route::get('/login', [\App\Http\Controllers\AuthController::class, 'showLoginForm'])->name('login');
    Route::post('/login_process', [\App\Http\Controllers\AuthController::class, 'login'])->name('login_process');

    Route::get('/register', [\App\Http\Controllers\AuthController::class, 'showRegisterForm'])->name('register');
    Route::post('/register_process', [\App\Http\Controllers\AuthController::class, 'register'])->name('register_process');

    Route::get('/forgot', [\App\Http\Controllers\AuthController::class, 'showForgotForm'])->name('forgot');
    Route::post('/forgot_process', [\App\Http\Controllers\AuthController::class, 'forgot'])->name('forgot_process');
});

// Route::post('/admin/states', \App\Http\Controllers\Admin\AcceptController::class, 'approve')->name('admin.approve');
// Route::post('/admin/states', \App\Http\Controllers\Admin\AcceptController::class, 'decline')->name('admin.decline');

resources/views/admin/states/accept.blade.php
@extends('layout.admin')

@section('title', 'Отправленные статьи')

@section('content')
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button> 
        <strong>{{ $message }}</strong>
</div>
@endif

<span>
    <strong><h1>Заявки<h4>(принятые)</h4></h1></strong>
</span>
    <br>
    <div>
    <a class="btn btn-info text-white" href="{{ route('admin.states.index') }}">На проверке</a>    <a class="btn btn-danger " href="{{ route('admin.states.reject') }}">Отклоненные</a>    <a class="btn btn-info" style="background-color:green;" href="{{ route('admin.states.accept') }}">Принятые</a>  
  </div>
    <input class="form-control mb-6" type="text" placeholder="Поиск" id="search-text" onkeyup="tableSearch()" style="width: 300px; float:right">
<div class="bg-color-blue">
    <table class="table" id="info-table">
        <thead>
            <tr>
            <th scope="col">ID</th> 
            <th scope="col">Титул</th>
            <th scope="col">Имя</th>
            <th scope="col">Email</th>
            <th scope="col">Номер</th>
            <th scope='col'>Cтатус</th>
            </tr>
        </thead>
        <tbody>
            
            @foreach($states as $state)
            @if($state->status == "Принят")
            <tr>
                <th scope="row">{{ $state->id }}
                    <td>{{ $state->user->dignity}}</td>
                    <td>{{ $state->short_name}}</td>
                    <td>{{ $state->user->email }}</td>
                    <td>{{ $state->user->number }}</td>
                    <td>{{ $state->status}}</td>
                      
                    <td class="d-flex gap-3 align-items-start">
                        <a href="{{ route('admin.states.show', $state->id) }}" class="btn btn-info text-white">Посмотреть</a>
                    
                        <a class="btn btn-info "  href="{{ route('admin.posts.create') }}" id="{{$state->id}}" style="background-color: green;">Опубликовать</a> 
                    </td>
                </th>
                </tr>
                @endif
            @endforeach
        </tbody>
    </table>
</div>

<script>
 function tableSearch() {
    var phrase = document.getElementById('search-text');
    var table = document.getElementById('info-table');
    var regPhrase = new RegExp(phrase.value, 'i');
    var flag = false;
    for (var i = 1; i < table.rows.length; i++) {
        flag = false;
        for (var j = table.rows[i].cells.length - 1; j >= 0; j--) {
            flag = regPhrase.test(table.rows[i].cells[j].innerHTML);
            if (flag) break;
        }
        if (flag) {
            table.rows[i].style.display = "";
        } else {
            table.rows[i].style.display = "none";
        }

    }
}
</script>

@endsection

resources/views/admin/states/create.blade.php
@extends('layout.admin')

@section('title', 'Добавить статью')

@section('content')
<div class="container mx-auto px-6 py-8">
    <h3 class="form_title mb-4">Добавить статью</h3>
        <div class="mt-8">
            <form enctype="multipart/form-data" class="space-y-5 mt-5" method="POST" action="{{ route('admin.states.store') }}">
                @csrf

                @if(isset($post))
                    @method('PUT')
                @endif

                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Главный автор:</label>
                    <input name="title" type="text" class="form_input" placeholder="" value="{{ $state->fio}}" ></input>
                </div>
                <!-- <input name="title" type="text" class="w-full h-12 border border-gray-800 rounded px-3 @error('title') border-red-500 @enderror" placeholder="Название" value="{{ $post->title ?? '' }}" />
 -->            <br>
                
                @error('title')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror
                @foreach($users as $user)
                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Orcid_id:</label>
                    <input name="preview" type="text" class="form_input" placeholder="" value="{{ $user->orcid_id}}" />
                </div>
                @endforeach
                <br>
                @error('preview')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Описание:</label>
                    <textarea name="description" type="text" class="form_input" placeholder="" value="{{ $post->description ?? '' }}"></textarea>
                </div>
                <br>
                @error('description')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror

                @if(isset($post) && $post->thumbnail)
                    <div>
                        <img class="h-64 w-64" src="{{ $post->thumbnail }}">
                    </div>
                @endif
                <br>
                <div  class="d-flex justify-content-center w-100 align-items-center gap-3">
                    <label for="" class="form_label">Файл</label>
                    <input name="thumbnail" type="file" class="form_input" placeholder="Файл"/>
                </div>

                @error('thumbnail')
                    <p class="text-red-500">{{ $message }}</p>
                @enderror
                <br>
                <div class="d-flex flex-column gap-2 w-100" style="max-width: 750px;">
                    <button type="submit" class="form_btn mx-auto text-decoration-none mt-5 padding-right-5">Сoxранить</button>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/states/index.blade.php
@extends('layout.admin')

@section('title', 'Отправленные статьи')

@section('content')
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button> 
        <strong>{{ $message }}</strong>
</div>
@endif

<span>
    <strong><h1>Заявки</h1><h4>(на проверке)</h4></strong>
</span>
    <br>
    <div>
    <a class="btn btn-info text-white" href="{{ route('admin.states.index') }}">На проверке</a>    <a class="btn btn-danger " href="{{ route('admin.states.reject') }}">Отклоненные</a>    <a class="btn btn-info" style="background-color:green;" href="{{ route('admin.states.accept') }}">Принятые</a>  
  </div>
    <input class="form-control mb-6" type="text" placeholder="Поиск" id="search-text" onkeyup="tableSearch()" style="width: 300px; float:right">
<div class="bg-color-blue">
    <table class="table" id="info-table">
        <thead>
            <tr>
            <th scope="col">ID</th> 
            <th scope="col">Титул</th>
            <th scope="col">Имя</th>
            <th scope="col">Email</th>
            <th scope="col">Номер</th>
            <th scope='col'>Cтатус</th>
            </tr>
        </thead>
        <tbody>
            
            @foreach($states as $state)
            @if($state->status == "Проверяется")
            <tr>
                <th scope="row">{{ $state->id }}
                    <td>{{ $state->user->dignity}}</td>
                    <td>{{ $state->short_name}}</td>
                    <td>{{ $state->user->email }}</td>
                    <td>{{ $state->user->number }}</td>
                    <td>{{ $state->status}}</td>
                      
                    <td class="d-flex gap-3 align-items-start">
                        <a href="{{ route('admin.states.show', $state->id) }}" class="btn btn-info text-white">Посмотреть</a>
                    
                        <a class="btn btn-info "  href="{{ route('admin.posts.create') }}" id="{{$state->id}}" style="background-color: green;">Опубликовать</a> 
                    </td>
                </th>
                </tr>
                @endif
            @endforeach
        </tbody>
    </table>
</div>
<script>
 function tableSearch() {
    var phrase = document.getElementById('search-text');
    var table = document.getElementById('info-table');
    var regPhrase = new RegExp(phrase.value, 'i');
    var flag = false;
    for (var i = 1; i < table.rows.length; i++) {
        flag = false;
        for (var j = table.rows[i].cells.length - 1; j >= 0; j--) {
            flag = regPhrase.test(table.rows[i].cells[j].innerHTML);
            if (flag) break;
        }
        if (flag) {
            table.rows[i].style.display = "";
        } else {
            table.rows[i].style.display = "none";
        }

    }
}
</script>

@endsection

resources/views/admin/states/reject.blade.php
@extends('layout.admin')

@section('title', 'Отправленные статьи')

@section('content')
<link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>

@if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button> 
        <strong>{{ $message }}</strong>
</div>
@endif

<span>
    <strong><h1>Заявки<h4>(отклоненные)</h4></h1></strong>
</span>
    <br>
    <div>
    <a class="btn btn-info text-white" href="{{ route('admin.states.index') }}">На проверке</a>    <a class="btn btn-danger " href="{{ route('admin.states.reject') }}">Отклоненные</a>    <a class="btn btn-info" style="background-color:green;" href="{{ route('admin.states.accept') }}">Принятые</a>  
  </div>
    <input class="form-control mb-6" type="text" placeholder="Поиск" id="search-text" onkeyup="tableSearch()" style="width: 300px; float:right">
<div class="bg-color-blue">
    <table class="table" id="info-table">
        <thead>
            <tr>
            <th scope="col">ID</th> 
            <th scope="col">Титул</th>
            <th scope="col">Имя</th>
            <th scope="col">Email</th>
            <th scope="col">Номер</th>
            <th scope='col'>Cтатус</th>
            </tr>
        </thead>
        <tbody>
            
            @foreach($states as $state)
            @if($state->status == "Отклонен")
            <tr>
                <th scope="row">{{ $state->id }}
                    <td>{{ $state->user->dignity}}</td>
                    <td>{{ $state->short_name}}</td>
                    <td>{{ $state->user->email }}</td>
                    <td>{{ $state->user->number }}</td>
                    <td>{{ $state->status}}</td>
                      
                    <td class="d-flex gap-3 align-items-start">
                        <a href="{{ route('admin.states.show', $state->id) }}" class="btn btn-info text-white">Посмотреть</a>
                    
                        <a class="btn btn-info "  href="{{ route('admin.posts.create') }}" id="{{$state->id}}" style="background-color: green;">Опубликовать</a> 
                    </td>
                </th>
                </tr>
                @endif
            @endforeach
        </tbody>
    </table>
</div>

<script>
 function tableSearch() {
    var phrase = document.getElementById('search-text');
    var table = document.getElementById('info-table');
    var regPhrase = new RegExp(phrase.value, 'i');
    var flag = false;
    for (var i = 1; i < table.rows.length; i++) {
        flag = false;
        for (var j = table.rows[i].cells.length - 1; j >= 0; j--) {
            flag = regPhrase.test(table.rows[i].cells[j].innerHTML);
            if (flag) break;
        }
        if (flag) {
            table.rows[i].style.display = "";
        } else {
            table.rows[i].style.display = "none";
        }

    }
}
</script>

@endsection

resources/views/admin/states/show.blade.php
@extends('layout.admin')

@section('title', "Редактировать пользователя ID {$state->id}")

@section('content')    
<h3 class="form_title mb-4"> Статья номер {{$state->id}}</h3>
<form enctype="multipart/form-data" class="space-y-5 mt-5" method="POST" action="{{ isset($state) ? route('admin.states.update', $state->id) : route('admin.states.store') }}">
    @csrf
    @if(isset($state))
         @method('PUT')
    @endif
<div class="col-12 d-flex gap-3 d-flex justify-content-around mt-4 flex-wrap">
    <div class="d-flex flex-column gap-3">
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Язык статьи:</label></label>
            <input name="stat_lang" type="text" class="form_input" value="{{$state->stat_lang}}" placeholder="" disabled>
        </div>
        
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Категория:</label></label>
            <input name="category" type="text" class="form_input" value="{{$state->category}}" placeholder="" disabled>
        </div>
        
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Тип статьи:</label></label>
            <input name="stat_type" type="text" class="form_input" value="{{$state->stat_type}}" placeholder="" disabled>
        </div>
        
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Интститут(ру):</label></label>
            <input name="institute_ru" type="text" class="form_input" value="{{$state->institute_ru}}" placeholder="" disabled>
        </div>
        
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Институт(уз):</label></label>
            <input name="institute_uz" type="text" class="form_input" value="{{$state->institute_uz}}" placeholder="" disabled>
        </div>
        
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Институт(анг):</label></label>
            <input name="institute_en" type="text" class="form_input" value="{{$state->institute_en}}" placeholder="" disabled>
        </div>

        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">ФИО:</label></label>
            <input name="short_name" type="text" class="form_input" value="{{$state->short_name}}" placeholder="" disabled>
        </div>

        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Файл</label></label>
            <a href="https://www.farmatsiya.uz/storage/app/public/{{$state->files}}" download>Скачать</a> 
        </div>
    </div>
    <div class="d-flex flex-column gap-3">
        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Ключевые слова</label></label>
            <input name="key_words" type="text" class="form_input" value="{{$state->key_words}}" placeholder="" >
        </div>

        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Aннотация</label></label>
            <textarea name="annotation" type="text" class="form_input" style="height:400px;" value="" placeholder="" disabled>{{$state->annotation}}</textarea>
        </div>

        <div  class="d-flex  w-100 align-items-center gap-3">
            <label for="" class="form_label">Действие</label></label>
            <select class="form-select" aria-label="Default select example" name="status" id="{{$state->id}}" >      
                <option name="sele" selected="Проверяется" value="Проверяется"{{ $state->state =="Проверяется" ? 'selected' : '' }} >Проверяется</option>
                <option name="sele" value="Принят" {{ $state->status =="Принят" ? 'selected' : '' }}>Принят</option>
                <option name="sele" value="Отклонен"{{ $state->status =="Отклонен" ? 'selected' : '' }}>Отклонен</option>           
            </select>         
        </div>
        <div class="d-flex flex-column gap-2 w-100" style="max-width: 750px;">
            <button type="submit" class="form_btn mx-auto text-decoration-none mt-5 padding-right-5">Сoxранить</button>
        </div>
    </div>
    @if ($message = Session::get('success'))
<div class="alert alert-success alert-block">
    <button type="button" class="close" data-dismiss="alert">×</button> 
        <strong>{{ $message }}</strong>
</div>
@endif
</div>
</form>
@endsection